---
title: "Visuals"
author: "Soumyadip"
date: "11/27/2019"
output: html_document
---
### Data Sources:
https://www.kaggle.com/new-york-state/nys-children-in-foster-care-annually
https://www.ncsc.org/Microsites/EveryKid/Home/Data-and-Reform-Efforts/Data-By-State.aspx
https://www.acf.hhs.gov/cb/resource/trends-in-foster-care-and-adoption

```{r message=FALSE, warning=FALSE}
library(readxl)
```

## Read the data
```{r}
state_data_served <- read_excel("data/afcars_state_data_tables_09thru18.xlsx", range = "Served!A8:K60")
head(state_data_served)
```

## Map Plot
https://socviz.co/maps.html
```{r}
library(maps)
us_states <- map_data("state")
head(us_states)
```

```{r}
library(mapproj)
ggplot(data = us_states, mapping = aes(x = long, y = lat, group = group, fill = region)) +
  geom_polygon(color = "gray90", size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  guides(fill=FALSE)
```

<!--chapter:end:Mitra_Visuals.Rmd-->

---
title: "FinalProject-FosterCare_Adoption"
output: 
  flexdashboard::flex_dashboard:
    source_code: embed
    theme: spacelab
    social: [ "twitter", "facebook", "menu" ]
---
```{r include=FALSE}
library(flexdashboard)
library(ggplot2)
library(tidyverse)
library(tidyr)
library(readxl)
```

```{r load-data-transformation}
#national dataset
nation_df<-read_excel("data/national_afcars_trends_2009_through_2018.xlsx",sheet="Data")

#State dataset
#Numbers of Children Served in Foster Care, by State
state_served <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="Served!A8:K60") %>%
gather(year,Served,'FY 2009':'FY 2018')

#Numbers of Children in Foster Care on September 30th, by State
state_inCare <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="In Care on September 30th!A8:K60") %>%
gather(year,InCare_Sep30,'FY 2009':'FY 2018')

#Numbers of Children Entering Foster Care, by State
state_entered <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="Entered!A8:K60") %>%
gather(year,entered,'FY 2009':'FY 2018')

#Numbers of Children Exiting Foster Care, by State
state_exited <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="Exited!A8:K60") %>%
gather(year,exited,'FY 2009':'FY 2018')

#Numbers of Children Waiting for Adoption, by State
state_waitingAdoption <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="Waiting for Adoption!A8:K60") %>%
gather(year,waiting_Adoption,'FY 2009':'FY 2018')

#Numbers of Children Waiting for Adoption Whose Parental Rights Have Been Terminated, by State
state_parentalRightsTerminated <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="Parental Rights Terminated!A8:K60") %>%
gather(year,parental_rights_terminated,'FY 2009':'FY 2018')

#Numbers of Children Adopted, by State
state_adopted <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="Adopted!A8:K60") %>%
gather(year,adopted,'FY 2009':'FY 2018')
```


```{r merge_data}
merge_cols<-c("State","year")
#The merge argument only takes two values as input, so you have to do them separately:
#state_df<- merge(state_served,state_inCare,state_entered,state_exited,state_waitingAdoption,state_parentalRightsTerminated,state_adopted,by=c("State","year"))

state_df<- merge(state_served,state_inCare,by=merge_cols)
state_df<- merge(state_df,state_entered,by=merge_cols)
state_df<- merge(state_df,state_exited,by=merge_cols)
state_df<- merge(state_df,state_waitingAdoption,by=merge_cols)
state_df<- merge(state_df,state_parentalRightsTerminated,by=merge_cols)
state_df<- merge(state_df,state_adopted,by=merge_cols)
```

<!--chapter:end:RamyaP_fostercare_adoption_annually.Rmd-->

