---
title: "FinalProject-FosterCare_Adoption"
output: 
  flexdashboard::flex_dashboard:
    source_code: embed
    theme: spacelab
    social: [ "twitter", "facebook", "menu" ]
---
```{r include=FALSE}
library(flexdashboard)
library(ggplot2)
library(tidyverse)
library(tidyr)
library(readxl)
```

```{r load-data-transformation}
#national dataset
nation_df<-read_excel("data/national_afcars_trends_2009_through_2018.xlsx",sheet="Data")

#State dataset
#Numbers of Children Served in Foster Care, by State
state_served <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="Served!A8:K60") %>%
gather(year,Served,'FY 2009':'FY 2018')

#Numbers of Children in Foster Care on September 30th, by State
state_inCare <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="In Care on September 30th!A8:K60") %>%
gather(year,InCare_Sep30,'FY 2009':'FY 2018')

#Numbers of Children Entering Foster Care, by State
state_entered <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="Entered!A8:K60") %>%
gather(year,entered,'FY 2009':'FY 2018')

#Numbers of Children Exiting Foster Care, by State
state_exited <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="Exited!A8:K60") %>%
gather(year,exited,'FY 2009':'FY 2018')

#Numbers of Children Waiting for Adoption, by State
state_waitingAdoption <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="Waiting for Adoption!A8:K60") %>%
gather(year,waiting_Adoption,'FY 2009':'FY 2018')

#Numbers of Children Waiting for Adoption Whose Parental Rights Have Been Terminated, by State
state_parentalRightsTerminated <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="Parental Rights Terminated!A8:K60") %>%
gather(year,parental_rights_terminated,'FY 2009':'FY 2018')

#Numbers of Children Adopted, by State
state_adopted <- read_excel("data/afcars_state_data_tables_09thru18.xlsx",range="Adopted!A8:K60") %>%
gather(year,adopted,'FY 2009':'FY 2018')
```


```{r merge_data}
merge_cols<-c("State","year")
#The merge argument only takes two values as input, so you have to do them separately:
#state_df<- merge(state_served,state_inCare,state_entered,state_exited,state_waitingAdoption,state_parentalRightsTerminated,state_adopted,by=c("State","year"))

state_df<- merge(state_served,state_inCare,by=merge_cols)
state_df<- merge(state_df,state_entered,by=merge_cols)
state_df<- merge(state_df,state_exited,by=merge_cols)
state_df<- merge(state_df,state_waitingAdoption,by=merge_cols)
state_df<- merge(state_df,state_parentalRightsTerminated,by=merge_cols)
state_df<- merge(state_df,state_adopted,by=merge_cols)
```


```{r ramyap-viz}

library(ggmap) # for theme_nothing

pie_selectdf<- state_df %>%
              filter(State=="California" & year=="FY 2010") %>%
              select(Served,InCare_Sep30,entered,exited,waiting_Adoption,parental_rights_terminated,adopted) %>%
              gather(indicators,count,'Served':'adopted')

df <- pie_selectdf %>%
   # factor levels need to be the opposite order of the cumulative sum of the count
   mutate(Group = factor(indicators, levels = c("Served","InCare_Sep30","entered","exited","waiting_Adoption","parental_rights_terminated","adopted")),
          cumulative = cumsum(count),
          midpoint = cumulative - count / 2,
          #label = paste0(Group, " ", round(count / sum(count) * 100, 1), "%"))
          label = paste0(round(count / sum(count) * 100, 1), "%"))

ggplot(df, aes(x = 1, weight = count, fill = indicators)) +
   geom_bar(width = 1, position = "stack") +
   coord_polar(theta = "y") +
   #geom_text(aes(x = 1.3, y = midpoint, label = label)) +
   geom_text(aes(x = 1, y = count, label = label),
                  position = position_stack(vjust = .6))+
   theme_void()  
```

```{r ramyap-viz}
library(ggplot2)
library(dplyr)
library(magrittr)
library(scales)


kids = read_excel('data/Child population by age group.xlsx')
```

```{r ramyap-viz}

kids_df<-kids %>%
         filter(LocationType=="State",TimeFrame==2010,DataFormat=="Number",AgeGroup=="0 to 4")


kids_df$Data <- type.convert(kids_df$Data)


sum_total_pop = sum(kids_df$Data)

firstLevel = kids_df %>% summarize(total_pop=sum(kids_df$Data))

sunburst_0 = ggplot(firstLevel)
sunburst_1 = sunburst_0 + 
  geom_bar(data=firstLevel, aes(x=1, y=total_pop), fill='darkgrey', stat='identity') +
  geom_text(aes(x=1, y=sum_total_pop/2, label=paste('Foster kids distribution in 2010', comma(total_pop))), color='white')
  
sunburst_1  + coord_polar('y')

loc_pop = kids_df %>% 
   group_by(Location) %>% 
   summarise(total_pop=sum(Data)) %>% 
   arrange(desc(total_pop))



```
```{r ramyap-viz}
compute_angle = function(perc){
  angle = -1
  #if(perc < 0.25) # 1st q [90,0]
    #angle = 90 - (perc/0.25) * 90
  #else if(perc < 0.5) # 2nd quarter [0, -90]
    #angle = (perc-0.25) / 0.25 * -90
  #else if(perc < 0.75) # 3rd q [90, 0]
    #angle = 90 - ((perc-0.5) / 0.25 * 90)
  #else if(perc < 1.00) # last q [0, -90]
    #angle = ((perc -0.75)/0.25) * -90

  if(perc < 0.5) {# 1st half [90, -90]
    angle = (180 - (perc/0.5) * 180) - 90
  }
  else{ # 2nd half [90, -90]
    angle = (90 - ((perc - 0.5)/0.5) * 180)
  }


  return(angle)
}


secondLevel = loc_pop %>%
  mutate(running=cumsum(total_pop), pos=running - total_pop/2)

print(secondLevel)
secondLevel = secondLevel %>% group_by(1:n())

secondLevel<-secondLevel[!is.na(secondLevel$running) & !is.na(secondLevel$pos),]


secondLevel = secondLevel %>%
  mutate(angle=compute_angle((running - total_pop/2) / sum_total_pop))

secondLevel= secondLevel %>%
             top_n(10)

```
```{r ramyap-viz}
secondLevel=secondLevel[1:10,]
```

```{r ramyap-viz}
sunburst_2 = sunburst_1 + geom_bar(data=secondLevel,
                                   aes(x=2, y=total_pop, fill=total_pop, stroke=3),
                                   color='white', position='stack', stat='identity')

```
```{r ramyap-viz}
sunburst_3 = sunburst_2 + geom_text(data=secondLevel, aes(label=paste(Location, comma(total_pop)), x=2, y=pos, angle=angle))
sunburst_3 + scale_y_continuous(labels=comma) + scale_fill_continuous(low='white', high='blue') + coord_polar('y') + theme_minimal()
```

```{r ramyap-viz}
devtools::install_github("timelyportfolio/sunburstR")

```
```{r ramyap-viz}
#devtools::install_github("timelyportfolio/sunburstR")

library(sunburstR)
# read in sample visit-sequences.csv data provided in source
# https://gist.github.com/kerryrodden/7090426#file-visit-sequences-csv

sunburst(read.csv(
  system.file("data/Child population by age group.csv")
  ,header=T
  ,stringsAsFactors = FALSE
))

```
